# Generated by Django 2.0.7 on 2018-07-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfolio',
            name='uploadAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porfolio',
            name='video',
            field=models.CharField(default='', max_length=512),
        ),
    ]
