# Generated by Django 2.0.7 on 2018-07-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180722_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfolio',
            name='artist',
            field=models.CharField(default='', max_length=200),
        ),
    ]
