# Generated by Django 2.0.7 on 2018-08-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image'),
        ('post', '0002_auto_20180819_1208'),
    ]

    operations = [
    ]
